services:
  - type: web
    name: temp-mail-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_server:app --host 0.0.0.0 --port 10000 & python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 7942960582:AAETZ5KvUiw9_SBoqocKGxqGt8SYbo00D70
